/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Bridge01.glb -o src/components/worldassets/Bridge01.tsx --transform --types 
Files: public/models/Bridge01.glb [18.25MB] > /Users/odaineforbes/Desktop/pathologic/src/components/worldassets/Bridge01-transformed.glb [518.75KB] (97%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh: THREE.Mesh
    Mesh_1: THREE.Mesh
  }
  materials: {
    Trunk_Atlas: THREE.MeshStandardMaterial
    Wooden_Structures: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Bridge01-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Mesh.geometry} material={materials.Trunk_Atlas} />
        <mesh geometry={nodes.Mesh_1.geometry} material={materials.Wooden_Structures} />
      </group>
    </group>
  )
}

useGLTF.preload('/Bridge01-transformed.glb')
