/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Bush02.glb -o src/components/worldassets/Bush02.tsx --transform --types 
Files: public/models/Bush02.glb [2.29MB] > /Users/odaineforbes/Desktop/pathologic/src/components/worldassets/Bush02-transformed.glb [150.29KB] (93%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Bush02: THREE.Mesh
  }
  materials: {
    Leaves_Atlas_02: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Bush02-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Bush02.geometry} material={materials.Leaves_Atlas_02} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/Bush02-transformed.glb')
