/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Colony_Alien_Sign_Art.glb -o src/components/worldassets/Colony_Alien_Sign_Art.tsx --transform --types 
Files: public/models/Colony_Alien_Sign_Art.glb [372.82KB] > /Users/odaineforbes/Desktop/pathologic/src/components/worldassets/Colony_Alien_Sign_Art-transformed.glb [31.16KB] (92%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Colony_Alien_Sign_Art: THREE.Mesh
  }
  materials: {
    Colony_Marbres_01_Mat: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Colony_Alien_Sign_Art-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Colony_Alien_Sign_Art.geometry} material={materials.Colony_Marbres_01_Mat} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/Colony_Alien_Sign_Art-transformed.glb')
