/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Flower03.glb -o src/components/worldassets/Flower03.tsx --transform --types 
Files: public/models/Flower03.glb [2.26MB] > /Users/odaineforbes/Desktop/pathologic/src/components/worldassets/Flower03-transformed.glb [266.62KB] (88%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Flower03: THREE.Mesh
  }
  materials: {
    Leaves_Atlas_03: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Flower03-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Flower03.geometry} material={materials.Leaves_Atlas_03} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/Flower03-transformed.glb')
