/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/PalmTree02.glb -o src/components/worldassets/PalmTree02.tsx --transform --types 
Files: public/models/PalmTree02.glb [14.15MB] > /Users/odaineforbes/Desktop/pathologic/src/components/worldassets/PalmTree02-transformed.glb [543.79KB] (96%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    PalmTree02: THREE.Mesh
    LeavePalmTree02_01: THREE.Mesh
  }
  materials: {
    PalmTree_Tree: THREE.MeshStandardMaterial
    Leaves_Atlas_03: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/PalmTree02-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.PalmTree02.geometry} material={materials.PalmTree_Tree} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LeavePalmTree02_01.geometry} material={materials.Leaves_Atlas_03} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/PalmTree02-transformed.glb')
