/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Plant_02_Art.glb -o src/components/worldassets/Plant_02_Art.tsx --transform --types 
Files: public/models/Plant_02_Art.glb [585.6KB] > /Users/odaineforbes/Desktop/pathologic/src/components/worldassets/Plant_02_Art-transformed.glb [70.84KB] (88%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plant_02_Art: THREE.Mesh
  }
  materials: {
    Plant_01_Mat: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Plant_02_Art-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plant_02_Art.geometry} material={materials.Plant_01_Mat} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/Plant_02_Art-transformed.glb')
