/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Robot-transformed.glb -o src/components/worldassets/Robot-transformed.tsx --transform --types 
Files: public/models/Robot-transformed.glb [67.43KB] > /Users/odaineforbes/Desktop/pathologic/src/components/worldassets/Robot-transformed-transformed.glb [66.62KB] (1%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Robot: THREE.Mesh
  }
  materials: {
    Robot: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Robot-transformed-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Robot.geometry} material={materials.Robot} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/Robot-transformed-transformed.glb')
