/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/SmallGrass01.glb -o src/components/worldassets/SmallGrass01.tsx --transform --types 
Files: public/models/SmallGrass01.glb [1.98MB] > /Users/odaineforbes/Desktop/pathologic/src/components/worldassets/SmallGrass01-transformed.glb [27.05KB] (99%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    SmallGrass01: THREE.Mesh
  }
  materials: {
    SmallGrass_Mat: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/SmallGrass01-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.SmallGrass01.geometry} material={materials.SmallGrass_Mat} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/SmallGrass01-transformed.glb')
