/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Stone05.glb -o src/components/worldassets/Stone05.tsx --transform --types 
Files: public/models/Stone05.glb [2.37MB] > /Users/odaineforbes/Desktop/pathologic/src/components/worldassets/Stone05-transformed.glb [254.28KB] (89%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Stone05: THREE.Mesh
  }
  materials: {
    Rock_Atlas: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Stone05-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Stone05.geometry} material={materials.Rock_Atlas} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/Stone05-transformed.glb')
