/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/TerrainGrass01.glb -o src/components/worldassets/TerrainGrass01.tsx --transform --types 
Files: public/models/TerrainGrass01.glb [10.3MB] > /Users/odaineforbes/Desktop/pathologic/src/components/worldassets/TerrainGrass01-transformed.glb [484.05KB] (95%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    TerrainGrass01: THREE.Mesh
  }
  materials: {
    Grass: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/TerrainGrass01-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.TerrainGrass01.geometry} material={materials.Grass} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/TerrainGrass01-transformed.glb')
