/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Tree04.glb -o src/components/worldassets/Tree04.tsx --transform --types 
Files: public/models/Tree04.glb [23.85MB] > /Users/odaineforbes/Desktop/pathologic/src/components/worldassets/Tree04-transformed.glb [668.86KB] (97%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh087: THREE.Mesh
    Mesh087_1: THREE.Mesh
  }
  materials: {
    Bush_Atlas_01: THREE.MeshStandardMaterial
    Trunk_Atlas: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Tree04-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Mesh087.geometry} material={materials.Bush_Atlas_01} />
        <mesh geometry={nodes.Mesh087_1.geometry} material={materials.Trunk_Atlas} />
      </group>
    </group>
  )
}

useGLTF.preload('/Tree04-transformed.glb')
