/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Tree01_Art.glb -o src/components/worldassets/Tree01_Art.tsx --transform --types 
Files: public/models/Tree01_Art.glb [1.72MB] > /Users/odaineforbes/Desktop/pathologic/src/components/worldassets/Tree01_Art-transformed.glb [135.26KB] (92%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    BezierCurve002: THREE.Mesh
    BezierCurve002_1: THREE.Mesh
    BezierCurve002_2: THREE.Mesh
    BezierCurve002_3: THREE.Mesh
    BezierCurve002_4: THREE.Mesh
    BezierCurve002_5: THREE.Mesh
  }
  materials: {
    Branches01: THREE.MeshStandardMaterial
    Branches02: THREE.MeshStandardMaterial
    Trunk01: THREE.MeshStandardMaterial
    Trunk02: THREE.MeshStandardMaterial
    Trunk03: THREE.MeshStandardMaterial
    Roots: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Tree01_Art-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.BezierCurve002.geometry} material={materials.Branches01} />
        <mesh geometry={nodes.BezierCurve002_1.geometry} material={materials.Branches02} />
        <mesh geometry={nodes.BezierCurve002_2.geometry} material={materials.Trunk01} />
        <mesh geometry={nodes.BezierCurve002_3.geometry} material={materials.Trunk02} />
        <mesh geometry={nodes.BezierCurve002_4.geometry} material={materials.Trunk03} />
        <mesh geometry={nodes.BezierCurve002_5.geometry} material={materials.Roots} />
      </group>
    </group>
  )
}

useGLTF.preload('/Tree01_Art-transformed.glb')
