/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Tree02.glb -o src/components/worldassets/Tree02.tsx --transform --types 
Files: public/models/Tree02.glb [26.8MB] > /Users/odaineforbes/Desktop/pathologic/src/components/worldassets/Tree02-transformed.glb [1.51MB] (94%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh085: THREE.Mesh
    Mesh085_1: THREE.Mesh
  }
  materials: {
    PalmTree_Tree: THREE.MeshStandardMaterial
    Tree_Topper02: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Tree02-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Mesh085.geometry} material={materials.PalmTree_Tree} />
        <mesh geometry={nodes.Mesh085_1.geometry} material={materials.Tree_Topper02} />
      </group>
    </group>
  )
}

useGLTF.preload('/Tree02-transformed.glb')
