/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Tree03.glb -o src/components/worldassets/Tree03.tsx --transform --types 
Files: public/models/Tree03.glb [20.65MB] > /Users/odaineforbes/Desktop/pathologic/src/components/worldassets/Tree03-transformed.glb [601.2KB] (97%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh086: THREE.Mesh
    Mesh086_1: THREE.Mesh
  }
  materials: {
    PalmTree_Tree: THREE.MeshStandardMaterial
    Tree_Topper01: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Tree03-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Mesh086.geometry} material={materials.PalmTree_Tree} />
        <mesh geometry={nodes.Mesh086_1.geometry} material={materials.Tree_Topper01} />
      </group>
    </group>
  )
}

useGLTF.preload('/Tree03-transformed.glb')
