create table if not exists public.exam_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'active'
    check (status in ('active', 'completed', 'abandoned')),
  question_count smallint not null
    check (question_count between 1 and 25),
  correct_count smallint not null default 0
    check (correct_count >= 0),
  score_percent numeric(5, 2),
  domain_stats jsonb not null default '{}'::jsonb,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  abandoned_at timestamptz
);

create table if not exists public.exam_session_items (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.exam_sessions(id) on delete cascade,
  item_id uuid not null references public.items(id) on delete restrict,
  order_index smallint not null check (order_index >= 0),
  domain text not null default 'Unknown',
  selected_choice_id text,
  is_correct boolean,
  time_spent_seconds smallint
    check (time_spent_seconds between 0 and 600),
  expired boolean not null default false,
  answered_at timestamptz,
  unique (session_id, order_index),
  unique (session_id, item_id)
);

create index if not exists exam_sessions_user_completed_idx
  on public.exam_sessions (user_id, completed_at desc);

create index if not exists exam_session_items_session_idx
  on public.exam_session_items (session_id, order_index);

alter table public.exam_sessions enable row level security;
alter table public.exam_session_items enable row level security;

drop policy if exists "Users can read their own exam sessions"
  on public.exam_sessions;
create policy "Users can read their own exam sessions"
  on public.exam_sessions
  for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Users can read their own exam answers"
  on public.exam_session_items;
create policy "Users can read their own exam answers"
  on public.exam_session_items
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.exam_sessions
      where exam_sessions.id = exam_session_items.session_id
        and exam_sessions.user_id = auth.uid()
    )
  );

